.eslintrc.json, packages/storage/package.json, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, packages/storage/src/utils/threadsUtils.spec.ts, packages/storage/src/utils/threadsUtils.ts, yarn.lock
This PR computes the deterministic threadId used to manage buckets belonging to a user. This would make space-sdk UserStorage compatible with space-daemon and existing users should be able to fetch existing data.
=> Feature: Set deterministic threadId for UserStorage buckets

changelogs/v0.0.2.md, etc/sdk.api.md, lerna.json, packages/sdk/README.md, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json, packages/users/src/identity/browserStorage.ts, packages/users/src/identity/fileStorage.ts, packages/users/src/users.ts, website/sidebars.json
This release adds more user and identity features to the space-sdk.
- `Users.backupKeysByPassphrase` - Backup existing identity using a passphrase.
- `Users.recoverKeysByPassphrase` - Recover existing identity using a passphrase.
- `UserStorage` logic has been updated to now fetch buckets in threads similar to existing
accounts created in the space-daemon. Existing accounts (identities) from space-daemon can
retrieve their data via the sdk.
=> Release: v0.0.2

integration_tests/storage_interactions.spec.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, packages/storage/src/utils/fsUtils.spec.ts, packages/storage/src/utils/fsUtils.ts
List directory response was not returning fields properly.  This adds the required parsing and formatting of response so that it aligns with the what the FE expects.
https://app.clubhouse.io/terminalsystems/story/21125/listdirectory-missing-fields
Which of the commands should be ran for updating the API docs?
=> Fix: list directory parsing errors/integration issues

changelogs/v0.0.5.md, etc/sdk.api.md, lerna.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json
This release contains some fixes to the logic of existing functionality.
- Manage Users Bucket Metadata with GunDB
- Track files mimetype. `UserStorage.addItems` request now requires specifying the files `mimeType`
and `UserStorage.openFile` returns the files `mimeType` in its response object.
- Fix `UserStorage.listDirectory`'s response to have compatible `date` and `address` fields.
=> Release: v0.0.5

etc/sdk.api.md, packages/storage/src/index.ts, packages/storage/src/metadata/gundbMetadataStore.spec.ts, packages/storage/src/metadata/gundbMetadataStore.ts, packages/storage/src/metadata/metadataStore.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, packages/storage/src/utils/threadsUtils.ts
This Fixes the GunDB Metadatastore logic and how user storage interacts with it. Now every new users bucket is created in a separate threadId, while the deterministic threadId is used as the password to authenticate the user in gundb.
=> Fix: Use different threads for users Id

etc/sdk.api.md, integration_tests/storage_interactions.spec.ts, packages/storage/package.json, packages/storage/src/errors.ts, packages/storage/src/metadata/gundbMetadataStore.spec.ts, packages/storage/src/metadata/gundbMetadataStore.ts, packages/storage/src/metadata/metadataStore.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, packages/storage/src/utils/pathUtils.spec.ts, packages/storage/src/utils/pathUtils.ts, yarn.lock
This PR implements features around managing storage file Uuid and being able to open a file by the uuid.
Fixes: ch21026, ch21029, ch21044
- [New feature (non-breaking change which adds functionality)
=> Features: File UUID management

changelogs/v0.0.6.md, etc/sdk.api.md, lerna.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json
This release contains some new features and fixes to logic of existing functionality.
- Features to file Uuid Management. Now `DirectoryEntry` has a `uuid` field. Check the response from `UserStorage.listDirectory`.
- New method [`UserStorage.openFileByUuid`](https://fleekhq.github.io/space-sdk/docs/sdk.userstorage.openfilebyuuid) can be used 
to open a file exclusively by its uuid. Note: uuid would throw an error if current SpaceUser is not authorized to access the file.
- New method [`UserStorage.txlSubscribe`]((https://fleekhq.github.io/space-sdk/docs/sdk.userstorage.txlsubscribe)) can be used to subcribe
to textile bucket events as user interacts with their bucket.
- More secure and privacy fix around users buckets. Now everyn users bucket has a different thread id.
Making it more …
=> Release: v0.0.6

integration_tests/storage_interactions.spec.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
Adds `dbId` and `bucket` to the `DirectoryEntry` type so it is returned as well.
Reported on slack by @gpuente
=> Hotfix: add dbid and bucket to directory entry.

etc/sdk.api.md, integration_tests/fixtures/configs.ts, integration_tests/storage_interactions.spec.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
Fetch and add DirectoryEntry to addItems results
Fixes: ch21233
=> Feature: Add DirectoryEntry to addItems results

etc/sdk.api.md, integration_tests/fixtures/configs.ts, integration_tests/storage_interactions.spec.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
Adds a progress callback to UserStorage.openFile methods to be notified on progress of fetching a file.
Fixes ch21234
=> Feature: Add progress callback to openFile and openFileByUuid

etc/sdk.api.md, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, packages/storage/src/utils/pathUtils.spec.ts
- Adds `Blob` as one of the supported types for uploading a file
- Adds an upload callback for `UserStorage.addItems()`.
=> Feature: Add upload callback and Add Blob to AddFileItem.data types

changelogs/v0.0.10.md, integration_tests/storage_interactions.spec.ts, lerna.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json
This release contains a fix with breaking changes.
No new features
- Default hub address is now production value, and correctly overriding the config
=> Release: v0.0.10

.eslintrc.json, packages/storage/package.json, packages/storage/src/metadata/gundbMetadataStore.ts, packages/storage/src/userStorage.ts, yarn.lock
This PR attempts to fix the issue with data always being resolved from the gundb metadatastore.
It also adds a `debugMode` option to the `UserStorage` class for exposing internal logs for further debugging.
=> Fix: FileMetadata UUID not always loading and debug logging mode

packages/storage/src/utils/streamUtils.ts
This PR fixes an issue where referencing the underlying buffer of the TypedArray returned from opening a file contains some extra noise. It does this by setting the initial data chunk through the typedarray set method instead of just assigning the typearray.
Unit tests pass and also tested via users interaction
=> Fix: Ensure consumeStream()'s underlying buffer matches data view

etc/sdk.api.md, integration_tests/storage_interactions.spec.ts, packages/storage/src/metadata/gundbMetadataStore.spec.ts, packages/storage/src/metadata/gundbMetadataStore.ts, packages/storage/src/metadata/metadataStore.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
This implements the `UserStorage.makeFilePublic()` to make a file at a path publicly accessible.
It does this by adding the file's uuid to a public users metadata store and it can be looked up through the `UserStorage.openFileByUuid()` function.
Fixes: ch20511
=> Feature: Make File Public

packages/storage/src/metadata/gundbMetadataStore.spec.ts, packages/storage/src/metadata/gundbMetadataStore.ts, packages/storage/src/metadata/metadataStore.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
Add bucketKey to metadata, populate members properly. NOTE: the originally expected metadata field on Textile's `ListPath` response is not returning the members. So this work around calls `PullPathAccessRoles` explicitly to retrieve members. We should still follow up with Textile and if we can get that data returned, we don't have to do this N+1 querying.
Fixes (issue): Unable to retrieve members.
=> Hotfix: add bucketKey to metadata, populate members properly.

changelogs/v0.0.15.md, etc/sdk.api.md, lerna.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json
This release contains a bug fix and is not backwards compatible due to upgrades to the metadata schema.
- The members field is actually populated now in `DirectoryEntry` items and also includes the `role` field
=> Release v0.0.15

changelogs/v0.0.16.md, lerna.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json
This release contains a bug fix:
- `addMembersToPathItems` was not checking for empty input array so it was throwing for empty input
=> Release v0.0.16

etc/sdk.api.md, packages/storage/src/metadata/gundbMetadataStore.spec.ts, packages/storage/src/metadata/gundbMetadataStore.ts, packages/storage/src/metadata/metadataStore.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
This PR implements the functionaltiy of acceptingFileInvitation and tracking accepted files in the shared with me record of the users gundb metadata store.
Fixes [ch21018] & [ch20156]
=> Feature: Implement acceptFileInvitation and getFilesSharedWithMe 

integration_tests/fixtures/configs.ts, integration_tests/mailbox_interactions.spec.ts, integration_tests/sharing_interactions.spec.ts, integration_tests/storage_interactions.spec.ts, integration_tests/test.env, integration_tests/users_interactions.spec.ts, packages/storage/src/userStorage.ts
This change double checks if the mailbox field is set on the SDK and init's it if it is not found.  Even though the FE was initalizing it, for some reason the mailbox field was null so it was not sending the mails. This is a workaround so it re-inits it.  @perfectmak let me know if you spot anything that could be the underlying issue.
Sidenote: also updated integration tests so we can test on dev via env vars as needed.
Mail not sending during share.
=> Hotfix: init if mailbox is not set

etc/sdk.api.md, integration_tests/sharing_interactions.spec.ts, packages/storage/src/metadata/gundbMetadataStore.ts, packages/storage/src/metadata/metadataStore.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
This PR properly implements accepting and rejecting file invitations.
It also does some internal logic to update the notifications for a user based on the action performed on the invite.
Fixes [ch21018]
=> Feature: Implement handleFileInvitation for rejecting invitation

etc/sdk.api.md, packages/storage/src/metadata/gundbMetadataStore.ts
Expose a stub method for sync from a temporary shared key. So the stubbed method would go out with a release this morning.
=> Feature: Stub syncFromTempKey() method

integration_tests/sharing_interactions.spec.ts, packages/storage/src/userStorage.ts
Fixes issue where empty pub key fails the overall share because we need to filter on empty strings as well. 
=> Hotfix: empty pk should not fail overall share. 

changelogs/v0.0.22.md, lerna.json, packages/mailbox/package.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json, packages/utils/package.json
Releases a bug fix:
- Fixes `shareViaPublicKey` so that empty public keys do not cause a throw
=> Release v0.0.22

integration_tests/sharing_interactions.spec.ts, packages/storage/src/metadata/gundbMetadataStore.spec.ts, packages/storage/src/metadata/gundbMetadataStore.ts, packages/storage/src/metadata/metadataStore.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
This adds the `setNotificationsLastSeenAt` so the FE can set it.  And also `getNotifications` now returns this value properly.
https://app.clubhouse.io/terminalsystems/story/21022/setnotificationslastseenat
=> setNotificationsLastSeenAt and add the value to getNotifications call

changelogs/v0.0.23.md, etc/sdk.api.md, lerna.json, packages/mailbox/package.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json, packages/utils/package.json
Releases a new feature:
- Implements `setNotificationsLastSeenAt` so that it gets returned with `getNotifications` and can be used to diff new messages.
=> Release v0.0.23

etc/sdk.api.md, integration_tests/sharing_interactions.spec.ts, packages/mailbox/src/mailbox.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, packages/users/package.json, packages/users/src/users.ts, packages/utils/package.json, packages/utils/src/auth.ts, packages/utils/src/index.ts
This PR provides the actual implementation for `UserStorage.syncFromTempKey()`.
It also does some internal refactoring of some user authentication process to allow authentication of temp key user in order to sync.
It is ready for review, but still under testing
Fixes: ch21507
=> Feature: Implement UserStorage.syncFromTempKey

integration_tests/sharing_interactions.spec.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
Hotfix that converts pub keys on `DirectoryEntry` members so that it matches the format stored in identity sevice.
- [] I have made corresponding changes to the documentation
=> Hotfix: convert pub key for members.

integration_tests/sharing_interactions.spec.ts, packages/storage/src/sharing/sharing.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
Fixes UUID not matching between sharees and uses admin as the base role so that sharees can invite others.
=> Hotfix: use admin for sharing, and pass uuid through notifs

integration_tests/storage_interactions.spec.ts, packages/mailbox/package.json, packages/storage/package.json, packages/storage/src/types.ts, packages/storage/src/userStorage.ts, yarn.lock
This implements the move paths on the SDK.  It will take an array of source paths and an array of destination paths and line them up by index and perform the move. It will then produce an event in the returned event emitter for each move operation and then a finally summary with the count of move operations in the end.
https://app.clubhouse.io/terminalsystems/story/21555/sdk-move
NOTE: pending Textile release for true integration test.
=> Move paths: move paths sdk method with commented out textile call
