FleekHQ/space-sdk

packages/users/src/identity/fileStorage.ts, packages/users/src/users.spec.ts, packages/users/src/users.ts
Just to make node js test passing.
=> Experimental file storage for identities

integration_tests/storage_interactions.spec.ts, package.json, packages/storage/package.json, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, yarn.lock
This implements the `UserStorage.listDirectory` function of the space sdk.
Fixes ch20486
- Unit tests for the `listDirectory()` function on the UserStorage class
- Integration test to validate `listDirectory()` works to show results of a created Folder.
=> Feature: UserStorage.listDirectory

integration_tests/storage_interactions.spec.ts, packages/storage/src/errors.ts, packages/storage/src/index.ts, packages/storage/src/testHelpers.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, packages/storage/src/utils/streamUtils.spec.ts, packages/storage/src/utils/streamUtils.ts
Contains the implementation of `openFile` on the UserStorage class of the SDK.
=> Feature: UserStorage.openFile simple implemenation

integration_tests/storage_interactions.spec.ts, packages/storage/package.json, packages/storage/src/index.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, yarn.lock
This PR implements the addItems() methods of the UserStorage class, allowing users to upload files in various formats to their buckets.
=> Feature: UserStorage.addItems (Uploading Files)

.github/workflows/release.yml, CONTRIBUTING.md, changelogs/v0.0.1.md
The first release of the SDK Release PR.
=> Release: v0.0.1

changelogs/v0.0.4.md, lerna.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json
This release contains some fixes to logic of existing functionality.
No Features
- Fix `UserStorage.addItems` logic to publish `.on('data')` events for created folders.
- Fix `UserStorage.listDirectory`'s response to be compatible with daemon.
=> Release: v0.0.4

changelogs/v0.0.9.md, lerna.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json
This release contains some new features and breaking changes to logic of existing functionality.
- Added upload callback to `UserStorage.addItems()` input. The callback will be called with the total number of bytes uploaed.
- Add Blob to AddFileItem.data types 
No new Fixes
=> Release: v0.0.9

README.md, packages/sdk/README.md
=> Chore: Readme and texts

changelogs/v0.0.11.md, etc/sdk.api.md, lerna.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json
This release contains a fix with breaking changes.
- Added a `debugMode` to `UserStorage` class. `new UserStorage(user, { debugMode: true });`.
This will activate logging of internal operations for further debugging by the user.
- Fixes to ensure users file and bucket information are fully loaded before results are returned.
=> Release: v0.0.11

etc/sdk.api.md, packages/storage/src/types.ts, packages/storage/src/userStorage.ts, packages/storage/src/utils/stubUtils.ts
This adds mock implementations of these methods to the UserStorage class:
- getFilesSharedWithMe
- getFilesSharedByMe
- getFilesRecentlySharedWith
The actual implementation PR's are still pending.
=> Feature: Mock sharing methods

etc/sdk.api.md, integration_tests/sharing_interactions.spec.ts, packages/sdk/README.md, packages/storage/src/errors.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts, packages/storage/src/utils/assertUtils.spec.ts, packages/storage/src/utils/assertUtils.ts, packages/storage/src/utils/threadsUtils.spec.ts, packages/storage/src/utils/threadsUtils.ts
Implements ShareFilesViaPublicKey on the `UserStorage` class.
=> Feature: ShareFilesViaPublicKey

changelogs/v0.0.18.md, lerna.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json
This is a partial release for the purposes of integration testing.
- `ShareFilesViaPublicKeys`
- `acceptFileInvitation`
- `getFilesSharedWithMe`
=> Release v0.0.18

etc/sdk.api.md, packages/storage/src/metadata/gundbMetadataStore.ts, packages/storage/src/metadata/metadataStore.ts, packages/storage/src/userStorage.spec.ts, packages/storage/src/userStorage.ts
=> Feature: getSharedWithMe and getRecentlySharedWith

changelogs/v0.0.20.md, lerna.json, packages/mailbox/package.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json, packages/utils/package.json
This release contains a workaround so that mailbox's are initialized during usage as well.
=> Release v0.0.20

packages/storage/src/userStorage.ts
=> typo in docs

changelogs/v0.0.25.md, etc/sdk.api.md, lerna.json, packages/mailbox/package.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json, packages/utils/package.json
- Gives sharing permissions to sharees so they can also share or make public
- Saves UUID for files so that they are consistent across owner and sharees
=> Release v0.0.25

integration_tests/sharing_interactions.spec.ts, packages/storage/src/sharing/sharing.ts, packages/storage/src/userStorage.ts
=> Hotfix: Reshare shared file

integration_tests/sharing_interactions.spec.ts, packages/storage/src/types.ts, packages/storage/src/userStorage.ts
Fixes: Add dbId to MakeFilePublicRequest to make shared files public.
=> Fix: Add dbId to MakeFilePublicRequest to make shared files public

packages/storage/src/userStorage.ts
Fix empty members list in shared file entries
=> Fix: Fetch Members of ShareFiles

changelogs/v0.0.30.md, etc/sdk.api.md, lerna.json, packages/mailbox/package.json, packages/sdk/package.json, packages/storage/package.json, packages/users/package.json, packages/utils/package.json
This release contains the move functionality so that multiple files could be moved using the Space SDK
- Move command
=> Release v0.0.30
